/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jsvtsim_TFImpl */

#ifndef _Included_jsvtsim_TFImpl
#define _Included_jsvtsim_TFImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jsvtsim_TFImpl
 * Method:    svtsim_tf_del
 * Signature: (Ljsvtsim/tfsim_t;)V
 */
JNIEXPORT void JNICALL Java_jsvtsim_TFImpl_svtsim_1tf_1del
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jsvtsim_TFImpl
 * Method:    svtsim_tf_new
 * Signature: (I)Ljsvtsim/tfsim_t;
 */
JNIEXPORT jobject JNICALL Java_jsvtsim_TFImpl_svtsim_1tf_1new
  (JNIEnv *, jclass, jint);

/*
 * Class:     jsvtsim_TFImpl
 * Method:    svtsim_tf_outputCable
 * Signature: (Ljsvtsim/tfsim_t;)Ljsvtsim/cable_t;
 */
JNIEXPORT jobject JNICALL Java_jsvtsim_TFImpl_svtsim_1tf_1outputCable
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jsvtsim_TFImpl
 * Method:    svtsim_tf_plugInput
 * Signature: (Ljsvtsim/tfsim_t;Ljsvtsim/cable_t;)V
 */
JNIEXPORT void JNICALL Java_jsvtsim_TFImpl_svtsim_1tf_1plugInput
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     jsvtsim_TFImpl
 * Method:    svtsim_tf_procEvent
 * Signature: (Ljsvtsim/tfsim_t;)V
 */
JNIEXPORT void JNICALL Java_jsvtsim_TFImpl_svtsim_1tf_1procEvent
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jsvtsim_TFImpl
 * Method:    svtsim_tf_useMaps
 * Signature: (Ljsvtsim/tfsim_t;Ljsvtsim/wedgemaps_t;)V
 */
JNIEXPORT void JNICALL Java_jsvtsim_TFImpl_svtsim_1tf_1useMaps
  (JNIEnv *, jclass, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
