/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jsvtvme_SvtvmeImpl */

#ifndef _Included_jsvtvme_SvtvmeImpl
#define _Included_jsvtvme_SvtvmeImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_initialise
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1initialise
  (JNIEnv *, jclass);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_setGlobalFlag
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1setGlobalFlag
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_getGlobalFlag
 * Signature: (ILorg/omg/CORBA/IntHolder;)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1getGlobalFlag
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_openBoard
 * Signature: (Ljava/lang/String;II)Ljsvtvme/svtvme_t;
 */
JNIEXPORT jobject JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1openBoard
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_closeBoard
 * Signature: (Ljsvtvme/svtvme_t;)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1closeBoard
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_disableFisionErrorMessages
 * Signature: (Ljsvtvme/svtvme_t;)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1disableFisionErrorMessages
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_enableFisionErrorMessages
 * Signature: (Ljsvtvme/svtvme_t;)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1enableFisionErrorMessages
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_setBoardFlag
 * Signature: (Ljsvtvme/svtvme_t;II)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1setBoardFlag
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_getBoardFlag
 * Signature: (Ljsvtvme/svtvme_t;ILorg/omg/CORBA/IntHolder;)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1getBoardFlag
  (JNIEnv *, jclass, jobject, jint, jobject);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_setBoardDebugFile
 * Signature: (Ljsvtvme/svtvme_t;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1setBoardDebugFile
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_printObjects
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1printObjects
  (JNIEnv *, jclass, jint);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_probeSlot
 * Signature: (Ljava/lang/String;ILorg/omg/CORBA/IntHolder;Lorg/omg/CORBA/IntHolder;)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1probeSlot
  (JNIEnv *, jclass, jstring, jint, jobject, jobject);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_getBoardIdentifier
 * Signature: (Ljsvtvme/svtvme_t;Lorg/omg/CORBA/IntHolder;Lorg/omg/CORBA/IntHolder;)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1getBoardIdentifier
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_boardId
 * Signature: (Ljsvtvme/svtvme_t;)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1boardId
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_boardSn
 * Signature: (Ljsvtvme/svtvme_t;)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1boardSn
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_boardType
 * Signature: (Ljsvtvme/svtvme_t;)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1boardType
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_boardSlot
 * Signature: (Ljsvtvme/svtvme_t;)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1boardSlot
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_boardCrate
 * Signature: (Ljsvtvme/svtvme_t;Lorg/omg/CORBA/StringHolder;)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1boardCrate
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_boardName
 * Signature: (ILorg/omg/CORBA/StringHolder;)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1boardName
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_nSpy
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1nSpy
  (JNIEnv *, jclass, jint);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_getRegList
 * Signature: (IILorg/omg/CORBA/IntHolder;[I)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1getRegList
  (JNIEnv *, jclass, jint, jint, jobject, jintArray);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_getFifoList
 * Signature: (IILorg/omg/CORBA/IntHolder;[I)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1getFifoList
  (JNIEnv *, jclass, jint, jint, jobject, jintArray);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_getMemList
 * Signature: (IILorg/omg/CORBA/IntHolder;[I)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1getMemList
  (JNIEnv *, jclass, jint, jint, jobject, jintArray);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_getSpyList
 * Signature: (IILorg/omg/CORBA/IntHolder;[I)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1getSpyList
  (JNIEnv *, jclass, jint, jint, jobject, jintArray);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_stringToObject
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1stringToObject
  (JNIEnv *, jclass, jstring);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_objectName
 * Signature: (ILorg/omg/CORBA/StringHolder;)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1objectName
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_shortName
 * Signature: (ILorg/omg/CORBA/StringHolder;)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1shortName
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_longName
 * Signature: (ILorg/omg/CORBA/StringHolder;)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1longName
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_address
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1address
  (JNIEnv *, jclass, jint);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_nWords
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1nWords
  (JNIEnv *, jclass, jint);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_mask
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1mask
  (JNIEnv *, jclass, jint);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_shift
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1shift
  (JNIEnv *, jclass, jint);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_reset
 * Signature: (Ljsvtvme/svtvme_t;)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1reset
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_init
 * Signature: (Ljsvtvme/svtvme_t;)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1init
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_setTmode
 * Signature: (Ljsvtvme/svtvme_t;)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1setTmode
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_isTmode
 * Signature: (Ljsvtvme/svtvme_t;)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1isTmode
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_isHeld
 * Signature: (Ljsvtvme/svtvme_t;)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1isHeld
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_isEmpty
 * Signature: (Ljsvtvme/svtvme_t;I)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1isEmpty
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_isHold
 * Signature: (Ljsvtvme/svtvme_t;I)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1isHold
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_isFull
 * Signature: (Ljsvtvme/svtvme_t;I)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1isFull
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_getState
 * Signature: (Ljsvtvme/svtvme_t;ILorg/omg/CORBA/IntHolder;)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1getState
  (JNIEnv *, jclass, jobject, jint, jobject);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_setState
 * Signature: (Ljsvtvme/svtvme_t;II)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1setState
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_readFifoMode
 * Signature: (Ljsvtvme/svtvme_t;II[I)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1readFifoMode
  (JNIEnv *, jclass, jobject, jint, jint, jintArray);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_writeFifoMode
 * Signature: (Ljsvtvme/svtvme_t;II[I)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1writeFifoMode
  (JNIEnv *, jclass, jobject, jint, jint, jintArray);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_readMemory
 * Signature: (Ljsvtvme/svtvme_t;II[I)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1readMemory
  (JNIEnv *, jclass, jobject, jint, jint, jintArray);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_writeMemory
 * Signature: (Ljsvtvme/svtvme_t;II[I)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1writeMemory
  (JNIEnv *, jclass, jobject, jint, jint, jintArray);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_writeVerifyMemory
 * Signature: (Ljsvtvme/svtvme_t;II[IILorg/omg/CORBA/IntHolder;)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1writeVerifyMemory
  (JNIEnv *, jclass, jobject, jint, jint, jintArray, jint, jobject);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_checkMemory
 * Signature: (Ljsvtvme/svtvme_t;II[IILorg/omg/CORBA/IntHolder;)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1checkMemory
  (JNIEnv *, jclass, jobject, jint, jint, jintArray, jint, jobject);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_checkMemoryFragment
 * Signature: (Ljsvtvme/svtvme_t;III[IILorg/omg/CORBA/IntHolder;)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1checkMemoryFragment
  (JNIEnv *, jclass, jobject, jint, jint, jint, jintArray, jint, jobject);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_readMemoryFragment
 * Signature: (Ljsvtvme/svtvme_t;III[I)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1readMemoryFragment
  (JNIEnv *, jclass, jobject, jint, jint, jint, jintArray);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_writeMemoryFragment
 * Signature: (Ljsvtvme/svtvme_t;III[I)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1writeMemoryFragment
  (JNIEnv *, jclass, jobject, jint, jint, jint, jintArray);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_spyCounter
 * Signature: (Ljsvtvme/svtvme_t;I)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1spyCounter
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_isFrozen
 * Signature: (Ljsvtvme/svtvme_t;I)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1isFrozen
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_isWrapped
 * Signature: (Ljsvtvme/svtvme_t;I)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1isWrapped
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_deltaSpy
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1deltaSpy
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_resetSpy
 * Signature: (Ljsvtvme/svtvme_t;I)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1resetSpy
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_readSpyTail
 * Signature: (Ljsvtvme/svtvme_t;II[I)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1readSpyTail
  (JNIEnv *, jclass, jobject, jint, jint, jintArray);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_readAllSpy
 * Signature: (Ljsvtvme/svtvme_t;II[I)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1readAllSpy
  (JNIEnv *, jclass, jobject, jint, jint, jintArray);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_sortWordsInBuffer
 * Signature: ([II)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1sortWordsInBuffer
  (JNIEnv *, jclass, jintArray, jint);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_sortPacketsInBuffer
 * Signature: ([II)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1sortPacketsInBuffer
  (JNIEnv *, jclass, jintArray, jint);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_sendWord
 * Signature: (Ljsvtvme/svtvme_t;I)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1sendWord
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_sendDataOnce
 * Signature: (Ljsvtvme/svtvme_t;I[II)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1sendDataOnce
  (JNIEnv *, jclass, jobject, jint, jintArray, jint);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_sendDataLoop
 * Signature: (Ljsvtvme/svtvme_t;I[I)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1sendDataLoop
  (JNIEnv *, jclass, jobject, jint, jintArray);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_resendDataOnce
 * Signature: (Ljsvtvme/svtvme_t;)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1resendDataOnce
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_resendDataLoop
 * Signature: (Ljsvtvme/svtvme_t;)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1resendDataLoop
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_resendData
 * Signature: (Ljsvtvme/svtvme_t;)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1resendData
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_readFifo
 * Signature: (Ljsvtvme/svtvme_t;II[I)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1readFifo
  (JNIEnv *, jclass, jobject, jint, jint, jintArray);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_readAllFifo
 * Signature: (Ljsvtvme/svtvme_t;II[ILorg/omg/CORBA/IntHolder;)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1readAllFifo
  (JNIEnv *, jclass, jobject, jint, jint, jintArray, jobject);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_isLast
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1isLast
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_checkState
 * Signature: (Ljsvtvme/svtvme_t;II)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1checkState
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_testRegister
 * Signature: (Ljsvtvme/svtvme_t;I)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1testRegister
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_testMemory
 * Signature: (Ljsvtvme/svtvme_t;IIILorg/omg/CORBA/IntHolder;)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1testMemory
  (JNIEnv *, jclass, jobject, jint, jint, jint, jobject);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_testIDPROM
 * Signature: (Ljsvtvme/svtvme_t;)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1testIDPROM
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_readWord
 * Signature: (Ljsvtvme/svtvme_t;ILorg/omg/CORBA/IntHolder;)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1readWord
  (JNIEnv *, jclass, jobject, jint, jobject);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_writeWord
 * Signature: (Ljsvtvme/svtvme_t;II)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1writeWord
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_readWords
 * Signature: (Ljsvtvme/svtvme_t;I[II)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1readWords
  (JNIEnv *, jclass, jobject, jint, jintArray, jint);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_writeWords
 * Signature: (Ljsvtvme/svtvme_t;II[I)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1writeWords
  (JNIEnv *, jclass, jobject, jint, jint, jintArray);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_readWordsAl
 * Signature: (Ljsvtvme/svtvme_t;I[II)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1readWordsAl
  (JNIEnv *, jclass, jobject, jint, jintArray, jint);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_writeWordsAl
 * Signature: (Ljsvtvme/svtvme_t;II[I)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1writeWordsAl
  (JNIEnv *, jclass, jobject, jint, jint, jintArray);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_cksumMemory
 * Signature: (Ljsvtvme/svtvme_t;ILorg/omg/CORBA/IntHolder;)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1cksumMemory
  (JNIEnv *, jclass, jobject, jint, jobject);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_cksumBlock
 * Signature: (Ljsvtvme/svtvme_t;IIILorg/omg/CORBA/IntHolder;)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1cksumBlock
  (JNIEnv *, jclass, jobject, jint, jint, jint, jobject);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_AmsUcodeSetOption
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1AmsUcodeSetOption
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_AmsUcodeGen
 * Signature: ([II)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1AmsUcodeGen
  (JNIEnv *, jclass, jintArray, jint);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_rand
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1rand
  (JNIEnv *, jclass, jint);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_wedge_randomtest
 * Signature: (ILjava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1wedge_1randomtest
  (JNIEnv *, jclass, jint, jstring, jint, jint);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_teststand_randomtest
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1teststand_1randomtest
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_hf_fill_fram
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1hf_1fill_1fram
  (JNIEnv *, jclass, jint, jstring, jstring, jstring);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_getBoardType
 * Signature: (Ljsvtvme/svtvme_t;)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1getBoardType
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_length
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1length
  (JNIEnv *, jclass, jint);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_SpyRamId
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1SpyRamId
  (JNIEnv *, jclass, jint);

/*
 * Class:     jsvtvme_SvtvmeImpl
 * Method:    svtvme_probeId
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SvtvmeImpl_svtvme_1probeId
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
