/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jsvtvme_SpyImpl */

#ifndef _Included_jsvtvme_SpyImpl
#define _Included_jsvtvme_SpyImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jsvtvme_SpyImpl
 * Method:    svtvme_spy_getState
 * Signature: (ILorg/omg/CORBA/IntHolder;I)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SpyImpl_svtvme_1spy_1getState
  (JNIEnv *, jobject, jint, jobject, jint);

/*
 * Class:     jsvtvme_SpyImpl
 * Method:    svtvme_spy_resetState
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SpyImpl_svtvme_1spy_1resetState
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jsvtvme_SpyImpl
 * Method:    svtvme_spy_setState
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SpyImpl_svtvme_1spy_1setState
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     jsvtvme_SpyImpl
 * Method:    svtvme_spy_getFreezeGlobal
 * Signature: (Lorg/omg/CORBA/IntHolder;I)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SpyImpl_svtvme_1spy_1getFreezeGlobal
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     jsvtvme_SpyImpl
 * Method:    svtvme_spy_getFreezeBackplane
 * Signature: (Lorg/omg/CORBA/IntHolder;I)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SpyImpl_svtvme_1spy_1getFreezeBackplane
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     jsvtvme_SpyImpl
 * Method:    svtvme_spy_setFreeze
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SpyImpl_svtvme_1spy_1setFreeze
  (JNIEnv *, jobject, jint);

/*
 * Class:     jsvtvme_SpyImpl
 * Method:    svtvme_spy_releaseFreeze
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SpyImpl_svtvme_1spy_1releaseFreeze
  (JNIEnv *, jobject, jint);

/*
 * Class:     jsvtvme_SpyImpl
 * Method:    svtvme_spy_forceReleaseFreeze
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_SpyImpl_svtvme_1spy_1forceReleaseFreeze
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
