/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jsvtsim_AMSImpl */

#ifndef _Included_jsvtsim_AMSImpl
#define _Included_jsvtsim_AMSImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jsvtsim_AMSImpl
 * Method:    svtsim_ams_del
 * Signature: (Ljsvtsim/amssim_t;)V
 */
JNIEXPORT void JNICALL Java_jsvtsim_AMSImpl_svtsim_1ams_1del
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jsvtsim_AMSImpl
 * Method:    svtsim_ams_new
 * Signature: (I)Ljsvtsim/amssim_t;
 */
JNIEXPORT jobject JNICALL Java_jsvtsim_AMSImpl_svtsim_1ams_1new
  (JNIEnv *, jclass, jint);

/*
 * Class:     jsvtsim_AMSImpl
 * Method:    svtsim_ams_outputCable
 * Signature: (Ljsvtsim/amssim_t;)Ljsvtsim/Cable;
 */
JNIEXPORT jobject JNICALL Java_jsvtsim_AMSImpl_svtsim_1ams_1outputCable
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jsvtsim_AMSImpl
 * Method:    svtsim_ams_plugInput
 * Signature: (Ljsvtsim/amssim_t;Ljsvtsim/Cable;)V
 */
JNIEXPORT void JNICALL Java_jsvtsim_AMSImpl_svtsim_1ams_1plugInput
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     jsvtsim_AMSImpl
 * Method:    svtsim_ams_procEvent1
 * Signature: (Ljsvtsim/amssim_t;)V
 */
JNIEXPORT void JNICALL Java_jsvtsim_AMSImpl_svtsim_1ams_1procEvent1
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jsvtsim_AMSImpl
 * Method:    svtsim_ams_setUcode
 * Signature: (Ljsvtsim/amssim_t;I)V
 */
JNIEXPORT void JNICALL Java_jsvtsim_AMSImpl_svtsim_1ams_1setUcode
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     jsvtsim_AMSImpl
 * Method:    svtsim_ams_useMaps
 * Signature: (Ljsvtsim/amssim_t;Ljsvtsim/WedgeMaps;)V
 */
JNIEXPORT void JNICALL Java_jsvtsim_AMSImpl_svtsim_1ams_1useMaps
  (JNIEnv *, jclass, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
