/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jsvtsim_CableImpl */

#ifndef _Included_jsvtsim_CableImpl
#define _Included_jsvtsim_CableImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jsvtsim_CableImpl
 * Method:    svtsim_cable_new
 * Signature: ()Ljsvtsim/cable_t;
 */
JNIEXPORT jobject JNICALL Java_jsvtsim_CableImpl_svtsim_1cable_1new
  (JNIEnv *, jclass);

/*
 * Class:     jsvtsim_CableImpl
 * Method:    svtsim_cable_del
 * Signature: (Ljsvtsim/cable_t;)V
 */
JNIEXPORT void JNICALL Java_jsvtsim_CableImpl_svtsim_1cable_1del
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jsvtsim_CableImpl
 * Method:    svtsim_cable_copywords
 * Signature: (Ljsvtsim/cable_t;[II)V
 */
JNIEXPORT void JNICALL Java_jsvtsim_CableImpl_svtsim_1cable_1copywords
  (JNIEnv *, jclass, jobject, jintArray, jint);

/*
 * Class:     jsvtsim_CableImpl
 * Method:    svtsim_cable_addwords
 * Signature: (Ljsvtsim/cable_t;[II)V
 */
JNIEXPORT void JNICALL Java_jsvtsim_CableImpl_svtsim_1cable_1addwords
  (JNIEnv *, jclass, jobject, jintArray, jint);

/*
 * Class:     jsvtsim_CableImpl
 * Method:    svtsim_cable_addword
 * Signature: (Ljsvtsim/cable_t;I)V
 */
JNIEXPORT void JNICALL Java_jsvtsim_CableImpl_svtsim_1cable_1addword
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     jsvtsim_CableImpl
 * Method:    cable_ndata
 * Signature: (Ljsvtsim/cable_t;)I
 */
JNIEXPORT jint JNICALL Java_jsvtsim_CableImpl_cable_1ndata
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jsvtsim_CableImpl
 * Method:    cable_datum
 * Signature: (Ljsvtsim/cable_t;I)I
 */
JNIEXPORT jint JNICALL Java_jsvtsim_CableImpl_cable_1datum
  (JNIEnv *, jclass, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
