/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jsvtvme_AmsImpl */

#ifndef _Included_jsvtvme_AmsImpl
#define _Included_jsvtvme_AmsImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jsvtvme_AmsImpl
 * Method:    svtvme_ams_init
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_AmsImpl_svtvme_1ams_1init
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jsvtvme_AmsImpl
 * Method:    svtvme_ams_getState
 * Signature: (ILorg/omg/CORBA/IntHolder;I)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_AmsImpl_svtvme_1ams_1getState
  (JNIEnv *, jobject, jint, jobject, jint);

/*
 * Class:     jsvtvme_AmsImpl
 * Method:    svtvme_ams_resetState
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_AmsImpl_svtvme_1ams_1resetState
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jsvtvme_AmsImpl
 * Method:    svtvme_ams_setState
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_AmsImpl_svtvme_1ams_1setState
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     jsvtvme_AmsImpl
 * Method:    svtvme_ams_tModeEnable
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_AmsImpl_svtvme_1ams_1tModeEnable
  (JNIEnv *, jobject, jint);

/*
 * Class:     jsvtvme_AmsImpl
 * Method:    svtvme_ams_tModeStatus
 * Signature: (Lorg/omg/CORBA/IntHolder;I)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_AmsImpl_svtvme_1ams_1tModeStatus
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     jsvtvme_AmsImpl
 * Method:    svtvme_ams_writeToOutput
 * Signature: (II[II)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_AmsImpl_svtvme_1ams_1writeToOutput
  (JNIEnv *, jobject, jint, jint, jintArray, jint);

/*
 * Class:     jsvtvme_AmsImpl
 * Method:    svtvme_ams_outputFile
 * Signature: (ILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_AmsImpl_svtvme_1ams_1outputFile
  (JNIEnv *, jobject, jint, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
