/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jsvtsim_WedgeMapsImpl */

#ifndef _Included_jsvtsim_WedgeMapsImpl
#define _Included_jsvtsim_WedgeMapsImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jsvtsim_WedgeMapsImpl
 * Method:    wedgeMaps_new
 * Signature: ()Ljsvtsim/wedgemaps_t;
 */
JNIEXPORT jobject JNICALL Java_jsvtsim_WedgeMapsImpl_wedgeMaps_1new
  (JNIEnv *, jclass);

/*
 * Class:     jsvtsim_WedgeMapsImpl
 * Method:    wedgeMaps_free
 * Signature: (Ljsvtsim/wedgemaps_t;)V
 */
JNIEXPORT void JNICALL Java_jsvtsim_WedgeMapsImpl_wedgeMaps_1free
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jsvtsim_WedgeMapsImpl
 * Method:    svtsim_getRam
 * Signature: (Ljsvtsim/wedgemaps_t;I[III)I
 */
JNIEXPORT jint JNICALL Java_jsvtsim_WedgeMapsImpl_svtsim_1getRam
  (JNIEnv *, jclass, jobject, jint, jintArray, jint, jint);

/*
 * Class:     jsvtsim_WedgeMapsImpl
 * Method:    svtsim_crcRam
 * Signature: (Ljsvtsim/wedgemaps_t;I)I
 */
JNIEXPORT jint JNICALL Java_jsvtsim_WedgeMapsImpl_svtsim_1crcRam
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     jsvtsim_WedgeMapsImpl
 * Method:    svtsim_hitToSS
 * Signature: (Ljsvtsim/wedgemaps_t;I)I
 */
JNIEXPORT jint JNICALL Java_jsvtsim_WedgeMapsImpl_svtsim_1hitToSS
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     jsvtsim_WedgeMapsImpl
 * Method:    svtsim_ssEdge
 * Signature: (Ljsvtsim/wedgemaps_t;II)I
 */
JNIEXPORT jint JNICALL Java_jsvtsim_WedgeMapsImpl_svtsim_1ssEdge
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     jsvtsim_WedgeMapsImpl
 * Method:    svtsim_tfSS
 * Signature: (Ljsvtsim/wedgemaps_t;I)I
 */
JNIEXPORT jint JNICALL Java_jsvtsim_WedgeMapsImpl_svtsim_1tfSS
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     jsvtsim_WedgeMapsImpl
 * Method:    svtsim_initMaps
 * Signature: (Ljsvtsim/wedgemaps_t;ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jsvtsim_WedgeMapsImpl_svtsim_1initMaps
  (JNIEnv *, jclass, jobject, jint, jstring, jstring, jstring);

/*
 * Class:     jsvtsim_WedgeMapsImpl
 * Method:    svtsim_initFromMapSet
 * Signature: (Ljsvtsim/wedgemaps_t;ILjava/lang/String;JLjava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_jsvtsim_WedgeMapsImpl_svtsim_1initFromMapSet
  (JNIEnv *, jclass, jobject, jint, jstring, jlong, jstring, jboolean);

/*
 * Class:     jsvtsim_WedgeMapsImpl
 * Method:    svtsim_useHwSet
 * Signature: (Ljsvtsim/wedgemaps_t;ILjava/lang/String;JLjava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_jsvtsim_WedgeMapsImpl_svtsim_1useHwSet
  (JNIEnv *, jclass, jobject, jint, jstring, jlong, jstring, jboolean);

/*
 * Class:     jsvtsim_WedgeMapsImpl
 * Method:    maps_ssStrips
 * Signature: (Ljsvtsim/wedgemaps_t;I)I
 */
JNIEXPORT jint JNICALL Java_jsvtsim_WedgeMapsImpl_maps_1ssStrips
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     jsvtsim_WedgeMapsImpl
 * Method:    maps_dSSdz
 * Signature: (Ljsvtsim/wedgemaps_t;I)I
 */
JNIEXPORT jint JNICALL Java_jsvtsim_WedgeMapsImpl_maps_1dSSdz
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     jsvtsim_WedgeMapsImpl
 * Method:    maps_pattSS
 * Signature: (Ljsvtsim/wedgemaps_t;II)I
 */
JNIEXPORT jint JNICALL Java_jsvtsim_WedgeMapsImpl_maps_1pattSS
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     jsvtsim_WedgeMapsImpl
 * Method:    maps_wedge
 * Signature: (Ljsvtsim/wedgemaps_t;)I
 */
JNIEXPORT jint JNICALL Java_jsvtsim_WedgeMapsImpl_maps_1wedge
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
