/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jsvtsim_DictImpl */

#ifndef _Included_jsvtsim_DictImpl
#define _Included_jsvtsim_DictImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jsvtsim_DictImpl
 * Method:    svtsim_dict_new
 * Signature: (I)Ljsvtsim/dict_t;
 */
JNIEXPORT jobject JNICALL Java_jsvtsim_DictImpl_svtsim_1dict_1new
  (JNIEnv *, jclass, jint);

/*
 * Class:     jsvtsim_DictImpl
 * Method:    svtsim_dict_clone
 * Signature: (Ljsvtsim/dict_t;)Ljsvtsim/dict_t;
 */
JNIEXPORT jobject JNICALL Java_jsvtsim_DictImpl_svtsim_1dict_1clone
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jsvtsim_DictImpl
 * Method:    svtsim_dict_free
 * Signature: (Ljsvtsim/dict_t;)V
 */
JNIEXPORT void JNICALL Java_jsvtsim_DictImpl_svtsim_1dict_1free
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jsvtsim_DictImpl
 * Method:    svtsim_dict_hash
 * Signature: (Ljsvtsim/dict_t;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jsvtsim_DictImpl_svtsim_1dict_1hash
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     jsvtsim_DictImpl
 * Method:    svtsim_dict_add
 * Signature: (Ljsvtsim/dict_t;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jsvtsim_DictImpl_svtsim_1dict_1add
  (JNIEnv *, jclass, jobject, jstring, jstring);

/*
 * Class:     jsvtsim_DictImpl
 * Method:    svtsim_dict_query
 * Signature: (Ljsvtsim/dict_t;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jsvtsim_DictImpl_svtsim_1dict_1query
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     jsvtsim_DictImpl
 * Method:    svtsim_dict_addOptionString
 * Signature: (Ljsvtsim/dict_t;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jsvtsim_DictImpl_svtsim_1dict_1addOptionString
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     jsvtsim_DictImpl
 * Method:    svtsim_dict_addFile
 * Signature: (Ljsvtsim/dict_t;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jsvtsim_DictImpl_svtsim_1dict_1addFile
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     jsvtsim_DictImpl
 * Method:    svtsim_dict_addBlob
 * Signature: (Ljsvtsim/dict_t;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_jsvtsim_DictImpl_svtsim_1dict_1addBlob
  (JNIEnv *, jclass, jobject, jstring, jint);

/*
 * Class:     jsvtsim_DictImpl
 * Method:    svtsim_dict_dump
 * Signature: (Ljsvtsim/dict_t;)V
 */
JNIEXPORT void JNICALL Java_jsvtsim_DictImpl_svtsim_1dict_1dump
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jsvtsim_DictImpl
 * Method:    svtsim_dict_crc
 * Signature: (Ljsvtsim/dict_t;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_jsvtsim_DictImpl_svtsim_1dict_1crc
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     jsvtsim_DictImpl
 * Method:    svtsim_dict_parseVersion
 * Signature: (Ljava/lang/String;Lorg/omg/CORBA/IntHolder;Lorg/omg/CORBA/IntHolder;)I
 */
JNIEXPORT jint JNICALL Java_jsvtsim_DictImpl_svtsim_1dict_1parseVersion
  (JNIEnv *, jclass, jstring, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
