/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jsvtvme_AmImpl */

#ifndef _Included_jsvtvme_AmImpl
#define _Included_jsvtvme_AmImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jsvtvme_AmImpl
 * Method:    svtvme_am_Init
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_AmImpl_svtvme_1am_1Init
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jsvtvme_AmImpl
 * Method:    svtvme_am_TmodeStatus
 * Signature: (Lorg/omg/CORBA/IntHolder;I)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_AmImpl_svtvme_1am_1TmodeStatus
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     jsvtvme_AmImpl
 * Method:    svtvme_am_getState
 * Signature: (ILorg/omg/CORBA/IntHolder;I)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_AmImpl_svtvme_1am_1getState
  (JNIEnv *, jobject, jint, jobject, jint);

/*
 * Class:     jsvtvme_AmImpl
 * Method:    svtvme_am_resetState
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_AmImpl_svtvme_1am_1resetState
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jsvtvme_AmImpl
 * Method:    svtvme_am_setState
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_AmImpl_svtvme_1am_1setState
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jsvtvme_AmImpl
 * Method:    svtvme_am_sendOpCode
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_AmImpl_svtvme_1am_1sendOpCode
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jsvtvme_AmImpl
 * Method:    svtvme_am_writeToOutput
 * Signature: (I[II)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_AmImpl_svtvme_1am_1writeToOutput
  (JNIEnv *, jobject, jint, jintArray, jint);

/*
 * Class:     jsvtvme_AmImpl
 * Method:    svtvme_am_writeToInput
 * Signature: (I[II)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_AmImpl_svtvme_1am_1writeToInput
  (JNIEnv *, jobject, jint, jintArray, jint);

/*
 * Class:     jsvtvme_AmImpl
 * Method:    svtvme_am_outputFile
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_AmImpl_svtvme_1am_1outputFile
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     jsvtvme_AmImpl
 * Method:    svtvme_am_inputFile
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_AmImpl_svtvme_1am_1inputFile
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     jsvtvme_AmImpl
 * Method:    svtvme_am_read
 * Signature: (III[II)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_AmImpl_svtvme_1am_1read
  (JNIEnv *, jobject, jint, jint, jint, jintArray, jint);

/*
 * Class:     jsvtvme_AmImpl
 * Method:    svtvme_am_write
 * Signature: (III[II)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_AmImpl_svtvme_1am_1write
  (JNIEnv *, jobject, jint, jint, jint, jintArray, jint);

/*
 * Class:     jsvtvme_AmImpl
 * Method:    svtvme_am_write_good
 * Signature: (III[I[III)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_AmImpl_svtvme_1am_1write_1good
  (JNIEnv *, jobject, jint, jint, jint, jintArray, jintArray, jint, jint);

/*
 * Class:     jsvtvme_AmImpl
 * Method:    svtvme_am_read_good
 * Signature: (III[I[III)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_AmImpl_svtvme_1am_1read_1good
  (JNIEnv *, jobject, jint, jint, jint, jintArray, jintArray, jint, jint);

/*
 * Class:     jsvtvme_AmImpl
 * Method:    svtvme_am_downloadPattern
 * Signature: (IILjava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_AmImpl_svtvme_1am_1downloadPattern
  (JNIEnv *, jobject, jint, jint, jstring, jstring, jint);

/*
 * Class:     jsvtvme_AmImpl
 * Method:    svtvme_am_uploadPattern
 * Signature: (IILjava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_AmImpl_svtvme_1am_1uploadPattern
  (JNIEnv *, jobject, jint, jint, jstring, jstring, jint);

/*
 * Class:     jsvtvme_AmImpl
 * Method:    svtvme_am_comparePattern
 * Signature: (IILjava/lang/String;Ljava/lang/String;Lorg/omg/CORBA/IntHolder;I)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_AmImpl_svtvme_1am_1comparePattern
  (JNIEnv *, jobject, jint, jint, jstring, jstring, jobject, jint);

/*
 * Class:     jsvtvme_AmImpl
 * Method:    svtvme_am_downloadComparePattern
 * Signature: (IILjava/lang/String;Ljava/lang/String;Lorg/omg/CORBA/IntHolder;I)I
 */
JNIEXPORT jint JNICALL Java_jsvtvme_AmImpl_svtvme_1am_1downloadComparePattern
  (JNIEnv *, jobject, jint, jint, jstring, jstring, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
