/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jsvtsim_MrgSimImpl */

#ifndef _Included_jsvtsim_MrgSimImpl
#define _Included_jsvtsim_MrgSimImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jsvtsim_MrgSimImpl
 * Method:    svtsim_mrg_new
 * Signature: ()Ljsvtsim/mrgsim_t;
 */
JNIEXPORT jobject JNICALL Java_jsvtsim_MrgSimImpl_svtsim_1mrg_1new
  (JNIEnv *, jclass);

/*
 * Class:     jsvtsim_MrgSimImpl
 * Method:    svtsim_mrg_del
 * Signature: (Ljsvtsim/mrgsim_t;)V
 */
JNIEXPORT void JNICALL Java_jsvtsim_MrgSimImpl_svtsim_1mrg_1del
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jsvtsim_MrgSimImpl
 * Method:    svtsim_mrg_plugInput
 * Signature: (Ljsvtsim/mrgsim_t;ILjsvtsim/cable_t;)V
 */
JNIEXPORT void JNICALL Java_jsvtsim_MrgSimImpl_svtsim_1mrg_1plugInput
  (JNIEnv *, jclass, jobject, jint, jobject);

/*
 * Class:     jsvtsim_MrgSimImpl
 * Method:    svtsim_mrg_outputCable
 * Signature: (Ljsvtsim/mrgsim_t;)Ljsvtsim/cable_t;
 */
JNIEXPORT jobject JNICALL Java_jsvtsim_MrgSimImpl_svtsim_1mrg_1outputCable
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jsvtsim_MrgSimImpl
 * Method:    svtsim_mrg_procEvent
 * Signature: (Ljsvtsim/mrgsim_t;)I
 */
JNIEXPORT jint JNICALL Java_jsvtsim_MrgSimImpl_svtsim_1mrg_1procEvent
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
